### ISSUE TITLE
Move to org

### ISSUE THREAD

**Issue by iliakan** [lighthousand/javascript-tutorial-ro#1]
Hello @lighthousand  !

I'm making scripts to synchronize translations with the main version and add other useful automations. 

For the scripts to work, translations should be in a single organization <https://github.com/javascript-tutorial>.

There are also other benefits of having translations in a single org.

Please transfer the repository. All commits, authors, permissions etc will remain as is.

There are two variants:

1. I can do that by cloning-reimporting, but all issues will be lost. Technically that will be another github project. If that's ok, just let me know.

2. To keep the issues, two steps are needed:
  a. Visit <https://github.com/contact> and ask the support to "remove the fork status" from your repo, so that it's no longer a fork, but rather a standalone project. They usually answer within 1 day.
  b. In repo settings, at the bottom, choose "Transfer", write your repo name and "javascript-tutorial" org. 

Thanks! I'm working to make translations more convenient and easier for others to join.

**Comment by lighthousand** [comment]
Hello @iliakan !

Because there are no issues on this repo, I think it would be better if you would clone this one since it would be easier and faster.

**Comment by iliakan** [comment]
Done! https://github.com/javascript-tutorial/ro.javascript.info

**Comment by lighthousand** [comment]
Nice ! So I will be working on this one then. Should i remove the original repo ? So it won't be confusing for those who will translate in the future.
    On Sunday, April 14, 2019, 5:28:33 PM GMT+3, Ilya Kantor <notifications@github.com> wrote:  
 
 
Done! https://github.com/javascript-tutorial/ro.javascript.info

**Comment by iliakan** [comment]
I updated Readme, made it more human-friendly, removed other languages. 

Couldn't keep translation, sorry =( 
It's in the previous revision though.

**Comment by lighthousand** [comment]
No problem. I will translate it. Also it seems much more readable now :)
    On Tuesday, April 16, 2019, 3:59:46 PM GMT+3, Ilya Kantor <notifications@github.com> wrote:  
 
 
I updated Readme, made it more human-friendly, removed other languages.

Couldn't keep translation, sorry =(
It's in the previous revision though.
